### ISSUE TITLE
Steps in current readme remove runner home directory

### ISSUE THREAD

**Issue by banagale** [colpal/actions-clean#2]
If you run this using @v1 right now it will delete your runner and break your self-runner setup. 

I saw that the fix for this is the only other issue in this repo.

I also saw that there was a recent change to use v1 as rolling version tag.

I presume v1 is not picking up subsequent releases.

**Comment by nafarlee** [comment]
Hey! I didn't see this issue until moments ago (and in fact, I didn't actually expect to get any "public" users).

The v1 tag seems to be pointing to the latest released version successfully, so there is a good chance the issue you are facing still exists.

Let me make sure I understand the issue: you have files in your `$HOME` directory that you want to hold onto between runs, and this action deletes them?

**Comment by banagale** [comment]
Hey there--I think I may have ended up not using this. But IIRC it was wiping out the entire path of the runner. Could have been I had it misconfigured at the time.

**Comment by nafarlee** [comment]
Ah, understood. I would ordinarily link to our self-hosted runner configuration to allow comparison; maybe we are configuring something weird! However, it is within a private repository.

Hope you found something else that suited your needs!
